config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    authenticate :user, lambda { |user| user.admin? } do
      mount Searchjoy::Engine, at: "searchjoy"
    end

    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    resources :products do
      member do
        post :create_alternate_language
      end
    end

    resources :breakout_session_imports, only: [ :new, :create ]
    resources :external_conference_registration_imports, only: [ :new, :create ]

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root 'pages#show', page: 'home'
  resources :pages, param: :page, only: [:show]

  get '/403', to: 'pages#show', page: 'home', as: 'error_403'
  get '/cart', to: 'carts#my_cart', as: 'cart'
  get '/directory', to: 'directory#index'
  post '/directory/join', to: 'directory#join_directory'
  get '/directory/profile/:user_id', to: 'directory#profile',
    as: 'directory_profile'
  get '/aws_s3_auth', to: 'aws_services#aws_s3_auth'

  get '/admin/become/users/:id', to: 'admin/users#become',
    as: 'become_user'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :products, only: [:show, :index] do
    member do
      get :shipping
      get :change_language
    end
  end
  resources :users, only: [:show, :edit, :update] do

    collection do
      get :edit_profile
    end
    member do
      get :edit_address
      get :profile
    end
    resources :orders, only: [:index, :show], controller: 'users/orders'
    resources :materials, only: [:index], controller: 'users/materials'

    controller :feed_items do
      post :send_message
    end

    controller :feed_policies do
      patch :toggle_private_messages_enabled
      patch :toggle_user_blocked
    end

    patch :add_interest, to: 'interests#add_user_interest'

  end


  resources :orders, only: [:show, :update] do
    get 'success', on: :member
  end
  resources :line_items, only: [:create, :destroy]
  resources :charges, only: [:create]
  resources :posts, only: [:index, :show]
  post :join_newsletter, to: 'guests#join_newsletter'

  resources :breakout_sessions, only: [:show] do
    controller :feed_items do
      post :send_breakout_session_comment
    end
    post :join_session, to: 'breakout_sessions#join_session',
      as: 'join'
    resources :breakout_session_supplements, only: [ :create, :destroy ],
      shallow: true
  end

  resources :conferences, only: [:show] do
    member do
      resources :breakout_sessions, only: [ :new, :create ]
    end
  end

  resources :interests, only: [:show] do
    controller :feed_items do
      post :send_interest_comment
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'users', controllers: {
        sessions: 'api/v1/users/sessions',
        registrations: 'api/v1/users/registrations'
      }, skip: [ :omniauth_callbacks ]

      post '/users/:user_id/send_message', to: 'feed_items#send_message'
      resources :users, only: [] do
        member do
          resources :private_messages, only: [ :index ]
        end
      end

      resources :conferences, only: [:index, :show] do
        resources :images, only: [ :index, :create ]
        member do
          resources :breakout_sessions, only: [:index]
        end
      end

      resources :breakout_sessions, only: [:index, :show] do
        resources :comments, only: [ :index, :create ]
      end

      resource :aws_s3_auth, only: [:show]
    end
  end
  get '/api/v1/directory', to: 'directory#index', format: "json"
end

app/models/breakout_session.rb
class BreakoutSession < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  validates :name, presence: true

  belongs_to :conference

  # These are the possible options in the select, but a breakout
  # session is only ever associated with one timeslot.
  has_many :breakout_session_timeslots, through: :conference

  has_many :breakout_session_supplements
  has_one :breakout_session_location_timeslot
  has_one :location, through: :breakout_session_location_timeslot,
    source: :breakout_session_location

  has_many :organized_breakout_sessions
  has_many :organizers, through: :organized_breakout_sessions,
    source: :user
  has_many :breakout_session_attendances
  has_many :attendees, through: :breakout_session_attendances,
    source: :user
  has_many :opted_in_attendees, -> {
      where(opted_in_to_public_directory: true)
    },
    through: :breakout_session_attendances,
    source: :user
  has_many :comments, as: :feedable, class_name: 'FeedItems::Comment'

  delegate :name, :slug, :id, to: :conference, prefix: true, allow_nil: true
  delegate :name, to: :location, prefix: true,
    allow_nil: true
  delegate :start_time, :end_time, :day,
    to: :breakout_session_location_timeslot, allow_nil: true

  scope :approved, -> { where(approved: true) }
  scope :order_by_time, -> {
    self.includes(:breakout_session_location_timeslot)
      .order(
        <<-EOS.strip_heredoc.squish
          breakout_session_location_timeslots.day ASC,
          breakout_session_location_timeslots.start_time ASC
        EOS
      )
  }

end

app/controllers/api/v1/breakout_sessions_controller.rb
module Api
  module V1
    class BreakoutSessionsController < BaseController
      before_action :set_breakout_session,
        :require_approved_breakout_session, only: [:show]

      def index
        breakout_sessions = BreakoutSession.where(
          conference_id: params[:id]
        ).approved.order_by_time

        render json: breakout_sessions
      end

      def show
        render json: @breakout_session
      end

      private

      def set_breakout_session
        @breakout_session ||= BreakoutSession.find(params[:id])
      end

      def require_approved_breakout_session
        unless @breakout_session.approved
          render json: {
            meta: { errors: { message: [ 'resource not found' ] } }
          }, status: :not_found
        end
      end

    end
  end
end

app/controllers/breakout_sessions_controller.rb
class BreakoutSessionsController < ApplicationController
  before_action :set_breakout_session, only: [:show, :join_session]

  def new
    if current_user && OrganizedBreakoutSession.pluck(:user_id).include?(current_user.id)
      redirect_to directory_path, notice: t('breakout_sessions.errors.already_applied')
    else
      conference = Conference.find(params[:id])
      @breakout_session = BreakoutSession.new(conference: conference)
      @timeslots = @breakout_session.breakout_session_timeslots.
        order(:day, :start_time).available
    end
  end

  def create
    authenticate_user!
    conference = Conference.find(params[:id])
    @timeslot = BreakoutSessionLocationTimeslot.find(
      params[:breakout_session][:breakout_session_location_timeslot]
    )
    @breakout_session = BreakoutSession.new(breakout_session_params)
    @breakout_session.conference = conference
    @breakout_session.organizers << current_user
    if @breakout_session.save
      @timeslot.update!(breakout_session: @breakout_session)
      UsersMailer.new_breakout_session_application(@breakout_session.id)
        .deliver_later
      redirect_to directory_path, notice: t('.thank_you')
    else
      @timeslots = @breakout_session.breakout_session_timeslots.
        order(:day, :start_time).available
      flash.now[:error] = 'Please complete all fields.'
      render :new
    end
  end

  def show
    store_location_for(:user, breakout_session_path(@breakout_session))
    @comments = @breakout_session.comments
      .order(created_at: :desc)
      .page(params[:page] || 1)
      .per(15)
    @breakout_session_supplements =
      @breakout_session.breakout_session_supplements
    respond_to do |format|
      format.html
      format.json do
        render json: @breakout_session, root: 'breakout_session',
          each_serializer: BreakoutSessionSerializer, comments: @comments
      end
    end
  end

  def join_session
    authenticate_user!
    if @breakout_session.attendees.find_by(id: current_user.id)
      redirect_to :back, alert: t('.already_joined')
      return
    end
    unless current_user.opted_in_to_public_directory?
      redirect_to :back, alert: t(
        '.profile_must_be_listed_in_the_directory',
        directory_path: directory_path
      )
      return
    end
    @breakout_session.attendees << current_user
    @breakout_session.save
    redirect_to :back, notice: t('.joined_session')
  end

  private

  def set_breakout_session
    @breakout_session = BreakoutSession.find(
      params[:breakout_session_id] || params[:id])
  end

  def breakout_session_params
    params.require(:breakout_session).permit(
      :name, :description
    )
  end
end

app/views/breakout_sessions/new.html.haml
- content_for :title, "#{@breakout_session.conference_name} | Host Breakout Session"
- content_for :header_logo, 'false'

.container#new-breakout-session.m-t-3.simple-show-layout
  .row.title-section
    .col-md-3.hidden-sm-down
      -# = link_to "< Back",
      -#   conference_path(@breakout_session.conference_slug),
      -#   class: 'hidden-xs-down'
    .col-md-6
      %h1.text-center= t('.header')

  %hr.m-b-3
  .row.m-t-2
    .col-sm-12
      - if current_user.try(:opted_in_to_public_directory?)
        .row
          .col-sm-8.col-sm-offset-2
            = form_for @breakout_session do |f|
              .form-group
                = f.label :name, 'Breakout Session Name', class: 'form-label'
                = f.text_field :name, class: 'form-control'
              .form-group
                = f.label :description, class: 'form-label'
                = f.text_area :description, rows: 7, class: 'form-control'
              .form-group
                = f.label :breakout_session_location_timeslot,
                  'Location and Timeslot', class: 'form-label'
                = f.select :breakout_session_location_timeslot,
                  options_from_collection_for_select(@timeslots, 'id', 'select_name'),
                  {}, class: 'form-control'
              .form-group.text-xs-center
                = f.submit t('.submit'), class: "btn btn-cart"
      - else
        .text-xs-center
          %p= t('.unauthenticated_intro',
            conference_name: @breakout_session.conference_name)
          = link_to t('directory.actions.join'),
            directory_join_path(post_directory_join_path: new_breakout_session_path(@breakout_session.conference)),
            method: :post, class: 'btn btn-cart'
          %br
          %br
          %p= t('.unauthenticated_conclusion')

app/views/breakout_sessions/show.html.haml
- content_for :title, "#{@breakout_session.name} | Montessori Conference Breakout Sessions"
- content_for :header_logo, 'false'
- content_for :meta_tags do
  = meta_tags(title: "Breakout Session: #{@breakout_session.name}",
    image: asset_url("conferences/#{@breakout_session.conference_id}.png"),
    description: "#{@breakout_session.description || @breakout_session.name} at the #{@breakout_session.conference_name}")

.container#breakout-session.m-t-3.simple-show-layout
  .row.title-section
    .col-md-3.hidden-sm-down
      = link_to "< Back",
        conference_path(@breakout_session.conference_slug), class: 'hidden-xs-down'
    .col-md-6
      %h1.text-center= @breakout_session.name.upcase

  %hr.m-b-3
  .row.m-t-2
    .col-sm-9
      .card.m-b-2
        .row.information
          .col-sm-6
            %div
              %small DATE:
              = format_date(@breakout_session)
            %div
              %small SESSION TIME:
              = breakout_session_time(@breakout_session)
          .col-sm-6
            %div
              %small LOCATION:
              = format_location(@breakout_session)
            .organizers
              %small HOST:
              %span
                - @breakout_session.organizers.each do |organizer|
                  = link_to directory_profile_path(organizer.id), class: 'organizer' do
                    = organizer.full_name
        - if @breakout_session.description.present?
          .row.information
            .col-sm-12
              %p= @breakout_session.description

      - unless @breakout_session_supplements.empty?
        %h5 Breakout Session Documents
        %ul.list-unstyled
          - @breakout_session_supplements.each do |supplement|
            %li
              = link_to supplement.document_file_name, supplement.document.url,
                target: '_blank'
              - if @breakout_session.organizers.include?(current_user)
                |
                = link_to 'Remove File',
                  breakout_session_supplement_path(supplement),
                  method: :delete, class: 'warning-link'

      - if @breakout_session.organizers.include?(current_user)
        %hr
        %h5 Presenter-only Document Upload
        %p Upload your presentation or supplemental materials here.
        .row
          .col-sm-12
            = form_for [ @breakout_session, BreakoutSessionSupplement.new ],
              class: 'form' do |f|
              = f.file_field :document
              %br
              %br
              = f.submit 'Upload Document', class: 'btn btn-cart'
        %hr
        %br

      .help.card-block.m-b-2
        Please post questions or comments below leading up to the conference
        to help your host tailor their discussion to your interests! This
        discussion board will stay live after the conference for feedback and
        ongoing discussion.

      = render 'feed_items/comment_feed', comments: @comments,
        create_comment_url: breakout_session_send_breakout_session_comment_path(@breakout_session)

    .col-sm-3
      - if user_signed_in?
        - unless @breakout_session.opted_in_attendees.find_by(id: current_user.id)
          %section.join.m-t-2.m-b-3.text-center
            = form_tag breakout_session_join_path(@breakout_session) do
              = submit_tag 'JOIN SESSION', class: 'btn btn-cart'
      - else
        %section.join.m-t-2.m-b-3
          %h5.text-center Join Session
          %hr
          .text-xs-center= t('.sign_in_or_sign_up_html',
            sign_in: new_user_session_path, sign_up: new_user_registration_path)

      %section.right-user-list
        %h5.text-center Attendees
        %hr
        - audience_size = @breakout_session.opted_in_attendees.count
        - if audience_size > 0
          - limit = 15
          - @breakout_session.opted_in_attendees.order(created_at: :desc).limit(limit).each do |attendee|
            = link_to directory_profile_path(attendee.id), class: 'user-in-list' do
              .profile
                .avatar{style: "background-image:url(#{attendee.avatar.url(:thumb)})"}
                .name
                  = attendee.full_name
          - if audience_size > limit
            .text-center
              %i And #{ audience_size - limit } more
        - else
          %div.text-center No attendees