config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    authenticate :user, lambda { |user| user.admin? } do
      mount Searchjoy::Engine, at: "searchjoy"
    end

    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    resources :products do
      member do
        post :create_alternate_language
      end
    end

    resources :breakout_session_imports, only: [ :new, :create ]
    resources :external_conference_registration_imports, only: [ :new, :create ]

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root 'pages#show', page: 'home'
  resources :pages, param: :page, only: [:show]

  get '/403', to: 'pages#show', page: 'home', as: 'error_403'
  get '/cart', to: 'carts#my_cart', as: 'cart'
  get '/directory', to: 'directory#index'
  post '/directory/join', to: 'directory#join_directory'
  get '/directory/profile/:user_id', to: 'directory#profile',
    as: 'directory_profile'
  get '/aws_s3_auth', to: 'aws_services#aws_s3_auth'

  get '/admin/become/users/:id', to: 'admin/users#become',
    as: 'become_user'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :products, only: [:show, :index] do
    member do
      get :shipping
      get :change_language
    end
  end
  resources :users, only: [:show, :edit, :update] do

    collection do
      get :edit_profile
    end
    member do
      get :edit_address
      get :profile
    end
    resources :orders, only: [:index, :show], controller: 'users/orders'
    resources :materials, only: [:index], controller: 'users/materials'

    controller :feed_items do
      post :send_message
    end

    controller :feed_policies do
      patch :toggle_private_messages_enabled
      patch :toggle_user_blocked
    end

    patch :add_interest, to: 'interests#add_user_interest'

  end


  resources :orders, only: [:show, :update] do
    get 'success', on: :member
  end
  resources :line_items, only: [:create, :destroy]
  resources :charges, only: [:create]
  resources :posts, only: [:index, :show]
  post :join_newsletter, to: 'guests#join_newsletter'

  resources :breakout_sessions, only: [:show] do
    controller :feed_items do
      post :send_breakout_session_comment
    end
    post :join_session, to: 'breakout_sessions#join_session',
      as: 'join'
    resources :breakout_session_supplements, only: [ :create, :destroy ],
      shallow: true
  end

  resources :conferences, only: [:show] do
    member do
      resources :breakout_sessions, only: [ :new, :create ]
    end
  end

  resources :interests, only: [:show] do
    controller :feed_items do
      post :send_interest_comment
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'users', controllers: {
        sessions: 'api/v1/users/sessions',
        registrations: 'api/v1/users/registrations'
      }, skip: [ :omniauth_callbacks ]

      post '/users/:user_id/send_message', to: 'feed_items#send_message'
      resources :users, only: [] do
        member do
          resources :private_messages, only: [ :index ]
        end
      end

      resources :conferences, only: [:index, :show] do
        resources :images, only: [ :index, :create ]
        member do
          resources :breakout_sessions, only: [:index]
        end
      end

      resources :breakout_sessions, only: [:index, :show] do
        resources :comments, only: [ :index, :create ]
      end

      resource :aws_s3_auth, only: [:show]
    end
  end
  get '/api/v1/directory', to: 'directory#index', format: "json"
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  has_many :breakout_sessions
  has_many :breakout_session_locations
  has_many :breakout_session_timeslots, through: :breakout_session_locations
  has_many :images, as: :feedable, class_name: 'FeedItems::Image'
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_action :set_conference, only: [:show]

  def index
    @conferences = Conference.order(:created_at)
    respond_to do |format|
      format.html
      format.json { render json: @conferences }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @conference }
    end
  end

  private

  def set_conference
    @conference = Conference.find(params[:id])
  end
end

app/helpers/conferences_helper.rb
module ConferencesHelper

  def breakout_session_time(session)
    "#{format_time(session.start_time)} - #{format_time(session.end_time)}"
  end

  def format_date(session)
    return 'TBD' unless session.day
    session.day.strftime("%A %b %e")
  end

  def format_organizers(session)
    return 'TBD' if session.organizers.blank?
    session.organizers.map(&:full_name).reject(&:empty?).join(', ')
  end

  def format_location(session)
    return 'TBD' unless session.location
    session.location_name
  end

  private

  def format_time(time)
    return 'TBD' unless time.present?
    time.strftime("%H:%M")
  end
end

app/views/conferences/show.html.haml
- content_for :title, "#{@conference.name} | Montessori Conferences"
- content_for :header_logo, 'false'
- content_for :meta_tags do
  = meta_tags(title: "#{@conference.name}",
    image: asset_url("conferences/#{@conference.id}.png"),
    description: "#{@conference.name} in #{@conference.location}")

.container#conference.m-t-2
  .text-xs-center.m-b-2
    = image_tag 'leaf-rotated.png', alt: 'The Montessori Company Leaf',
      class: 'leaf'
  %h1.text-center.m-b-1= @conference.name.upcase
  .text-xs-center.m-b-2
    = image_tag 'leaf.png', alt: 'The Montessori Company Leaf',
      class: 'leaf'
  .row
    .col-sm-12
      %h5.m-b-1 Breakout Sessions
      %table.table.table-hover
        %thead
          %tr
            %th Name
            %th Day
            %th Time
            %th Organizer
            %th Location
        %tbody
          - @conference.breakout_sessions.approved.order_by_time.each do |session|
            %tr{onclick: "document.location = '#{breakout_session_path(session)}'"}
              %td
                = truncate(session.name, length: 65, separator: ' ')
              %td
                = format_date(session)
              %td
                = breakout_session_time(session)
              %td
                = format_organizers(session)
              %td
                = format_location(session)
  -# .row
  -#   .col-sm-4
  -#     = link_to t('breakout_sessions.actions.apply'),
  -#       new_breakout_session_path(@conference),
  -#       class: 'btn btn-primary btn-cart'