config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    authenticate :user, lambda { |user| user.admin? } do
      mount Searchjoy::Engine, at: "searchjoy"
    end

    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    resources :products do
      member do
        post :create_alternate_language
      end
    end

    resources :breakout_session_imports, only: [ :new, :create ]
    resources :external_conference_registration_imports, only: [ :new, :create ]

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root 'pages#show', page: 'home'
  resources :pages, param: :page, only: [:show]

  get '/403', to: 'pages#show', page: 'home', as: 'error_403'
  get '/cart', to: 'carts#my_cart', as: 'cart'
  get '/directory', to: 'directory#index'
  post '/directory/join', to: 'directory#join_directory'
  get '/directory/profile/:user_id', to: 'directory#profile',
    as: 'directory_profile'
  get '/aws_s3_auth', to: 'aws_services#aws_s3_auth'

  get '/admin/become/users/:id', to: 'admin/users#become',
    as: 'become_user'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :products, only: [:show, :index] do
    member do
      get :shipping
      get :change_language
    end
  end
  resources :users, only: [:show, :edit, :update] do

    collection do
      get :edit_profile
    end
    member do
      get :edit_address
      get :profile
    end
    resources :orders, only: [:index, :show], controller: 'users/orders'
    resources :materials, only: [:index], controller: 'users/materials'

    controller :feed_items do
      post :send_message
    end

    controller :feed_policies do
      patch :toggle_private_messages_enabled
      patch :toggle_user_blocked
    end

    patch :add_interest, to: 'interests#add_user_interest'

  end


  resources :orders, only: [:show, :update] do
    get 'success', on: :member
  end
  resources :line_items, only: [:create, :destroy]
  resources :charges, only: [:create]
  resources :posts, only: [:index, :show]
  post :join_newsletter, to: 'guests#join_newsletter'

  resources :breakout_sessions, only: [:show] do
    controller :feed_items do
      post :send_breakout_session_comment
    end
    post :join_session, to: 'breakout_sessions#join_session',
      as: 'join'
    resources :breakout_session_supplements, only: [ :create, :destroy ],
      shallow: true
  end

  resources :conferences, only: [:show] do
    member do
      resources :breakout_sessions, only: [ :new, :create ]
    end
  end

  resources :interests, only: [:show] do
    controller :feed_items do
      post :send_interest_comment
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'users', controllers: {
        sessions: 'api/v1/users/sessions',
        registrations: 'api/v1/users/registrations'
      }, skip: [ :omniauth_callbacks ]

      post '/users/:user_id/send_message', to: 'feed_items#send_message'
      resources :users, only: [] do
        member do
          resources :private_messages, only: [ :index ]
        end
      end

      resources :conferences, only: [:index, :show] do
        resources :images, only: [ :index, :create ]
        member do
          resources :breakout_sessions, only: [:index]
        end
      end

      resources :breakout_sessions, only: [:index, :show] do
        resources :comments, only: [ :index, :create ]
      end

      resource :aws_s3_auth, only: [:show]
    end
  end
  get '/api/v1/directory', to: 'directory#index', format: "json"
end

app/views/layouts/header/_messages.html.haml
.container
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
        %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
        = content_tag :div, msg.html_safe, :id => "flash_#{name}"

app/views/layouts/header/_navbar.html.haml
%nav.navbar.navbar-light
  .container
    %button{class: "navbar-toggler hidden-sm-up", type: "button",
      :data => { toggle: "collapse", target: "#collapsing-navbar"}}
      &#9776;
    .collapse.navbar-toggleable-xs#collapsing-navbar
      %ul.nav.navbar-nav
        %li.nav-item
          = link_to 'Home', root_path, class: 'nav-link'
        %li.nav-item
          = link_to 'About', page_path(:about), class: 'nav-link'
        %li.nav-item
          = link_to 'The Marketplace', products_path, class: 'nav-link'
        %li.nav-item
          = link_to 'The Montessori Directory', directory_path,
            class: 'nav-link'
        %li.nav-item
          -# This is temporary since we only have one conference. In the future
          -# we'll likely have a conference index page.
          - conference = Conference.find_by(id: 1) || Conference.create
          = link_to 'IMC Prague 2017', conference_path(conference),
            class: 'nav-link'
        -# %li.nav-item
        -#   = link_to 'Free Materials',
        -#     page_path('free-montessori-materials-printables'),
        -#     class: 'nav-link'
        - if user_signed_in?
          %li.nav-item.pull-sm-right
            = link_to 'Logout', destroy_user_session_path, method: :delete,
              class: 'nav-link'
          %li.nav-item.pull-sm-right
            = link_to 'Account', user_materials_path(current_user),
              class: 'nav-link'
        - else
          %li.nav-item.pull-sm-right
            = link_to 'Login', new_user_session_path, class: 'nav-link'
        -# %li.nav-item
        -#   = link_to 'Directory',
        -#     directory_path,
        -#     class: 'nav-link'
        %li.nav-item.pull-sm-right
          = link_to 'My Cart', cart_url, class: 'my-cart',
            data: { turbolinks: false }
= render 'shared/header'